### ISSUE TITLE
Trial testing

### ISSUE THREAD

**Issue by slashfan888** [Wikitude/wikitude-targets-api-samples#1]
1. enter my token.
2. run TargetAPITest.html
Always give me the "Error:error". Why?

**Comment by AndreasHauserWikitude** [comment]
The Targets API is no longer maintained.
Please have a look at the [RESTful API of Wikitude's CloudRecognition](http://www.wikitude.com/external/doc/documentation/latest/cloudrecognition/examples.html#examples) - It allows you to create a TargetCollection, add targets and generate a WTC file out of it.
You can then even watch your uploaded assets in [new Wikitude Studio](targetmanager.wikitude.com) and modify the assets manually.

API Documentation:
http://www.wikitude.com/external/doc/documentation/latest/Reference/Cloud%20Recognition%20REST%20API/index.html
